### ISSUE TITLE
[Feedback] Service Design

### ISSUE THREAD

**Issue by GoatMonarch** [FTL13/New-FTL13#104]
Staring up a series as we can have a documentation and open discusion about design for diferent departments.

Since service is pretty open ended I will merely list jobs a majority of the time, and then listing for diferent ways for the departments to co-operate if it's relevant.

Chef: Pratically nothing much needs changing. If we implement an economy system simmilar to /TG/ or not it'll pratically remain the same.

Botanist: I've heard talks about down sizing this department and combine it with the kitchen, though I will go indept about this in another [Feedback] thread.
Botanists are currently in a good possition, able to grow whatever they wish, and considering in the rebase they won't need to grow anything for R&D (as long we do not attain the Floyd Science "Pattent pending" rework) is reworked in a better direction. We can ensure that they get additional SoP to ensure co-operation betwen botany and the bartender as well, considering they are able to write off everything requested to them.

Bartender: Currently in a bad spot due to low population numbers on the server leading to alot of bartenders to never see a single customer. Though the same thing happens on TG and other servers durring low pop. Hopefully this department will become more usefull in the future.
One could also have a discusion about the botanist being able to directly transfer drinks to diferent departments on request.

Bartender/Botanist/Chef: A more open department would likely be a boon. I do not mean to combine their departments into one such as on the Ineese, but to instead increase the number of airlocks betwen the departments for currently on most maps they are either too far from one another, or just have windoors to access one another. Implementing an airlock on the Aetherwhisp map so they can quickly just travel to one another would be great for improving relations betwen the three jobs.

Chaplain: Current issue with this department is that the chaplain is seemingly unloved by the mappers at times, nearly half of our maps do not even have a chapel, so the chaplain can't access their nullrod, and holy water vial. One way to improve their enjoy ment would be to give them access to ways to mass drive away uncloneable and deceased crewmembers and to give them a supply of caskets (1-4 won't really need that big of a room considering deceased crewmembers are low in quantity currently.)

To increase the number of funnerals we could implement a MedicalDoctor SoP stating that they may not decline the Chaplain's request to uphold a funneral for an uncloneable corpse, considering alot of MedicalDoctors are actually handing over the corpse to the chef. 

Curator: Currently they are in a relatively fine possition as long they get their own equipment and a back room for the writing of books. We should keep in mind that part of their job is also to be somewhat inspired by Indiana Jones, and pottentionaly allow them to engage in FOB missions, to attain artifacts. (Though we should make it clear that one refined diamond is fair game, but puting an x-ray laser on display instead of handing it over to security should be handled the same as a miner not handing over the equipment. And stowing away an item without permision to be deemed as theft relevant to the item's vallue and importance to the department. Example: A black box's data disk which is worth 1000 credits is no small theft.)

Lawyer: Ensure under SoP that a security officer MUST respect the request for an investigation as long the prissoner is under a few circumstances currently in the lawyer's SoP. Misstreatment if prissoners and ignoring of lawyers have been a plague and needs to be stoped.
Do note that a trial is not always aviable, but the Executive Officer should also be aviable to stand in as a judge in the captain's stead if requested.

I also wish to make it clear that SoP should be upheld as a reason to demote someone from their work possition, as such if an officer or head of security declines a Trial for no good reason, the HoS/Captain/Executive Officer/ Nanotrasent can demote them if they wish.
Hopefully this will improve the lawyer's work experience, and lead to way less "Lawyers are useless for nobody listens to them" kind of talk.

Janitor: Currently in a good possition and is likely not in need of any change to keep their interests. We just need more corpses to spread blood, and with the event changes transportation of corpses will increase the work they have to do.

Clown: Return the ability to change their job name to Morale Technician, or Jester. Otherwise they are in a great possition with the current SoP and job role.

Mime: A mime should be exempt from shiplaw if they are engaged in a subjective art activity, such as writing messages onto the floor, and other acts. If requested the mime should be able to explain what they are doing art.
(Though if a mime breaks into the captains office because it's "art" admins should be notified of the act if done extensively.)

**End statments:**
I think if these things were implemented the departments would improve. Currently most of the departments are in a good possition but a bit of polishing in SoP and mapping could improve the departments greatly. And sadly most of the actual issues is due to low player numbers, which should be fixed once the rebase is fixed.

If Papa Flob or anybody else has something to add to this you are greatly encuraged to ping Goat Monarch/Honk Monarch on Discord, or to write a reply on this page. **HONK!**

**Comment by Vasily2013** [comment]
Chef: In my opinion there should be more available resources for the chef to make meals for lizard crew. right now items can be somewhat limited.

Chaplain: I can agree that it might add to RP value to let the chaplain hold funerals for uncloneable crew, and, from a Medical department view, agree that having such actions would be good. It helps empty out the morgue.

Janitor: No need to clean up blood if people actually use body bags/roller beds/chairs

Lawyer: Overall I agree, having them actually be able to hold Sec accountable would be good. Perhaps a way for them to directly write reports to centcomm or register formal complaints that don't just get thrown in a drawer would be a good idea.

**Comment by GoatMonarch** [comment]
As for the low sum of food aviable for for lizard crew will depend on how they are handling flavour codes for lizards, though I am glad to attain feedback about the kitchen from a chef main.

As for the Janitor they are in a relatively nice possition, there  will only be more stuff to clean up considering that nobody uses bodybags and the like.

As for Lawyer we could implement more authority into their job given we replace them with an Internal Afairs Agent, but that is unlikely to be an extreme in priority currently.

**Comment by Qustinnus** [comment]
Most service jobs are being sized down, a largecpart of new ftl13 is smaller crews and ships

**Comment by GoatMonarch** [comment]
> Most service jobs are being sized down, a largecpart of new ftl13 is smaller crews and ships

So you intend to downsize how manny people we got in diferent departments so it fits with our currentl 15~ player count along with downsizing the map as a whole? I think we'll keep a more stable playerbase if we make every department more fun to play on if we ensure every department has things to do.

If you look at the Aetherwhisp the botany department is too large for one person, but a good size for two botanists, if you downsize it and ensure only one botanist you can make that small area work really well.

What do you intend to do if we get too manny players and only assistants are more or less aviable?

**Comment by Qustinnus** [comment]
15 to 30 players, all roles that dont serve enough purpose get canned until they are made interesting enough.

**Comment by GoatMonarch** [comment]
I'd say that the Aetherwhisp as we currently have it would be a good fit, you can just remove useless roles and what not, and if we potentionaly have a bigger player base we can have another map with less restrictions. But I can see what you intend.
Though I believe that Botany and the bar while being able to be down sized should not be merged with the kitchen, just half them in size (And open job possitions) and we will likely not hear any complaints from the playerbase.

**Comment by Qustinnus** [comment]
The plan is to make the game focused on smaller ships and most of these ships are still made with so much extra things in mind. We have zero need for jobs such as chaplain, curator, mime and lawyer. I don't mind a few of these jobs staying, but they are not worth creating even bigger ships for.

**Comment by Qustinnus** [comment]
And the botany and bar will be merged with the kitchen, the previous idea was to remove botany so this is already a less strict measure.

**Comment by Altangy** [comment]
I agree fully with just putting service all in one job slot (or at least fewer slots). There's actually a lot of food items that lizards can eat, it's just chefs mostly make burgers because burgers.
