### ISSUE TITLE
[Feedback] Science Design

### ISSUE THREAD

**Issue by GoatMonarch** [FTL13/New-FTL13#105]
A quick page to talk about design changes for the Science department.

Research Director: Mostly the same as Scientist which is later mentioned, but they need SoP improvements. Needing the Captain's approval and another head's approval rarely happens, as such the AI will go the shift without any law changes, unless they get an ION event. Make it so the Research Director needs to state the command crew what changes they are making, but are not required to have the captain's or other head's approval.
This might seem like a drastic change, but currently captains all of the time declines even the chance of changing the AI's laws, and in most cases only the captains gets into the AI core to change the laws.
The RD should be the one handling the AI and a captain should only do so if no Research  Director/no capable science crewmember is onboard.

Roboticist: Currently in a good possition not really in need for much change.

Scientist: Majority of issues R&D has will be fixed once we have rebased, only issue is the scarcity of lava planets. Depending on what ship exploration system we will implement I can come up with two ideas.

The FTL:Faster Than Light aproach: Follow a linear path towards the end goal, we get a big grid that you attemt to travel to the other side of while having a hostile fleet following after you after each jump. If this is what we go for we should ensure that you are able to know what star has a lava planet surounding it, that you can drop down and mine on. To actually make miners enjoy their time do not make the fleet follow after you as you are remaining and mining. This will also change how someone will route their travel to the other side including distress signals and what not. (Including whenever or not the planet is ringed or ringless is also important, because they can either risk mining on a planet hoping it's a ringed planet with only diamonds and uranium, or have bad luck and only finding iron and silver. With this data they can take risks in the case they have already mined.)

The more current aproach: Hard code so there's always a (ringless) lava planet in the NT capital. The start of every round is focused on finding a lava planet. Might as well speed it up.

Why do I think only these two should be focused on, instead of finding matterials from event spawns?
1: Events are random, so you can go an entire shift without geting minnerals, making mining grumpy and the science team go braindead because there's fuck all to do.
2: Not only science/cargo will care about matterials. R&D rework will make every department have their own protolathe. As such every other department will have a worse shift due to RNG.
3: Making unique items be found on distress signals will have mining far more happy as they will actually gain something more. An item that recharges slowly and makes you blue space teleport randomly? Just implement tendrill loot into exploration events? Will go indept in the Cargo department, but this is a great improvement, instead of finding a gun which you need to give to security.

This is more or less the only current changes we'll need. Of course we will have to clean up their SoP's later. (Instance: RD is not required to hand over all weapons to the MaA because they will not be able to produce any weapons in RnD due to their protolate not being a security protolate. )

Edit: Creating end statement.

**End statement:**
Science is currently one of the departments in one of the better possitions, and will more or less only be improved in the future. Of course Floyd might wish to make a rework for Science in the future, but it should not be a top priority currently, and of course will be debated about once it's being worked on.
And most of the changes to improve this department is cargo related.

**Comment by Vasily2013** [comment]
Idea for the RD SOP change regarding weapons: Instead of setting it in their SOP that they have to turn weapons over to the MaA, just change it so the RD gets a weapons permit on their ID, thus removing the issue.

**Comment by GoatMonarch** [comment]
> Idea for the RD SOP change regarding weapons: Instead of setting it in their SOP that they have to turn weapons over to the MaA, just change it so the RD gets a weapons permit on their ID, thus removing the issue.

Though I'd agree we could do well with such a change as R&D looks now, but with the new rewrite we'll lose the ability for Science to make a majority of weapons, suposedly only the temprature gun will be something the science crew can produse that is deemed a weapon.
