### ISSUE TITLE
[Feedback] Engineering Design

### ISSUE THREAD

**Issue by GoatMonarch** [FTL13/New-FTL13#106]
Creating a page where we can discus the design we wish to see in the New-FTL code.

Atmos technician: Currently in a good state, and with multi-layered pipes atmostechnicians as long they maintain an atmos department with all the usual gasses (Example: Aetherwhisp) will be aviable, but on a much smaller scale if we implement multi-layered pipes. Generaly in a good position, but depending on what engine changes we'll have in the future atmos as a whole might be less important.
Also, the inclusion of new gasses could make a SM engine more fun to handle, but for the record we will not have a SM engine anymore. Otherwise the atmos engineers could try and create different gasses as they wish.

Engineer: Is map subjective, as long there's room to make improvements to areas onboard the ship, or to make other personal projects this is in a great possition. One issue that might appear is with how Floyd wishes to design a new engine which I will state lastly in this discusion. 

Cheif Engineer: This is simmilar to Engineer, but this is critical that the engine we intend to implement to be less dangerous than a SM, and alot more easier to handle.

**The engine room:**
So currently Floyd is considering a new engine that will do the following (as far I understand):
Take less time to set up.
Be less of a risk for the crew.
Balance weapons on energy output. (This last issue is just something to configure with once the code is in place.)

This means that we'll have to throw the SM to the side as it won't really fit into two of these goals, set up time, and the risk factor. Currently as far he has described it, it is a fission reactor that you merely have to turn it on using a button. The issue with this is the fact that the engine will be extremely simple, and as such will decrease the engine ideas drastically for the engineering crew, or occasional clown that makes a really stupid engine. 
As such I have the following as an idea: 
Creating a fission engine depending on gasses to go in a loop. Heavily inspired by the TEG, it'll just have two inputs and require gasses to rotate in a loop around it, depending on what gasses are in the pipe and what heat is in it.
Lets say for instance that hydrogen goes into one, and Carbon dioxide into the other. You super cool the carbon dioxide and as such it increases in energy output. More advanced /TG/ gasses could function as a superior gass to be injected in one hole or the other, as such keeping the engine setup intresting, but way faster as you only have to ensure pumps are on, and you've injected the right vollume and quantity of gasses into each pipe. 

Instead of turning on pumps, dragging over canisters, making more canisters, fixing an air alarm's options, and having the risk of it blowing up.
You can also ensure water vapour actually is something you're able to inject into the engine to have the clown manically laugh as they actually make an engine that uses water vapour to run, or to include water vapour as a gass bi-product.

I am very vague I know, but I think someone as Altangy/Sergei or another engineering main on FTL13 could come up exactly how the gasses interact with one another. But if we give different gasses their own interactions this could become a very intresting engine idea that the CE can toy around with.

**Ending Statement:**
Engineering as a whole with building mechanics will not change that much when the rewrite is done, but with Floyd's disatifaction with how the SM works, and how he wishes to change to another engine type this is probably the best of a compromise. Though I will note that it's not a high importance to create a new engine for the department to become more and fun to use, with new interactions of the SM if we just carried over using our current Engine it'd mix it up well and remain intresting.

**Comment by Qustinnus** [comment]
The SM might stay due to overhwhelming support, however, all ship machines will no longer use power as a means of balance.

**Comment by GoatMonarch** [comment]
Understandable, glad you're listening to player feedback related to the SM engine (and to be frank I barely know anything about the engine.)
Anyhow, I believe this thread won't need to be overly active because as much I am aware of the plans related to this department, nothing will negatively be changed.

**Comment by Qustinnus** [comment]
at worst the jobs will be merged

**Comment by Dennok** [comment]
Creating a simple "ready to go from a start" engine with a relatively low output power  is a good idea.
But need keep ability to create own SM or another engine, sm shard can by obtayned from the stantion, and maby add small chance to get SM crystal.
Anyway SM is infinite source of plasma and oxygen, not only power. It can help make ship self sustain.But SM very dangerous in battles, only one hit in the pipe and dont cooled SM engine can blow in minutes.

**Comment by Vasily2013** [comment]
I agree, having a ready at round start engine configuration is probably satisfactory to Floyd, and it keeps the SM engine in, something that is pretty core to engineers as it stands. However, there's one simple problem with that. It's a Mapper issue, not a Coding issue.

**Comment by Qustinnus** [comment]
stop reposting that it's a mapping issue continuously because it's not. The SM can still Delam after one hit. Dennok has the most viable option atm

**Comment by Vasily2013** [comment]
Qustinnus, I was referencing the issue of being easy to set up, not the issue that SM is rather dangerous when the shields drop. I'm talking about roundstart delams because people just wrench things into place and press go. That itself is a mapper issue in presenting a potential setup at round start that does not function.

**Comment by GoatMonarch** [comment]
> Qustinnus, I was referencing the issue of being easy to set up, not the issue that SM is rather dangerous when the shields drop. I'm talking about roundstart delams because people just wrench things into place and press go. That itself is a mapper issue in presenting a potential setup at round start that does not function.

While true Aerwhisp is going to have to make a new ship map once the code is into place meaning you can bring it up to them once we've actually completed the code where Aerwhisp gets the green light to start mapping away.

**Comment by Altangy** [comment]
Players "Wrenching and going" is not a mapping issue it's a player issue. It takes all of 10 minutes to look at the wiki and go "Huh, plasma burns and makes more plasma and thus makes more burn... and if everything is based off of percentages... I should put something that isn't plasma in there...". I've actually switched out canisters at round start and still have had players round start delam.

**Comment by Dennok** [comment]
We can use antimatter engine, it in code and work.
