### ISSUE TITLE
[Feedback] FTL13 Cargo system.

### ISSUE THREAD

**Issue by GoatMonarch** [FTL13/New-FTL13#5]
Change: One change in our re-write I'd suggest is to expand the general pool of items purchasable from different space stations. 
Why: While the chance of finding items might be fun at first mostly ruins any kind of plans you can make with cargo, you can never start of a shift wanting to do a bee botany shift without making the move towards cargo, checking the console, or by asking over the radio and hope it's possible. While you can work around the RNG of every station is by purchasing a yellow page book and then locate the perfect station no captain will ever fly across the galaxy for a bee keeper starter kit, and as such I've found it that pratically nobody uses cargo for it's purpuses of suplying the ship with resources and intresting items.

I therefore think keeping the way you purchase items of stations to remain for it is a rather unique and fun thing in all actuallity, but removing the random item pool of every station. (Though I could see a functioning cargo department if you restricted the random pool to expensive hard to attain items such as bikes and random collectible hat crates, but I do not see any bonuses from such a system.)

While I do not think this change will randomly make cargo the most active department in the universe I think it can only bring bonuses to the department in FTL13.

**Comment by Qustinnus** [comment]
There's a high chance of cargo being removed and being re-worked into a more generic thing on the side.

**Comment by GoatMonarch** [comment]
Allright, hope that the re-worked cargo system will be onpart if not superior to what we got currently. Supose I will give feedback when the time comes. 👌

**Comment by TMTIME** [comment]
We could have both our current cargo system, as well as this meme
https://github.com/FTL13/New-FTL13/blob/master/code/modules/cargo/expressconsole.dm

If we have it so going to the station and trading is a little cheaper than normal, then seems fair to me.

**Comment by Qustinnus** [comment]
Auroran cargo system is good but I want to reduce the size of cargos department and the amount of jobs as crew can handle this job mostly themselves. Maybe a designated  FoB crew that's kitted as a mix of miners and scientists

**Comment by GoatMonarch** [comment]
I would say that Tmtime's idea is likely superior, if nto a mix of the two would work well. The FoB is usualy kitted as a team effort with miners communicating, they got a RnD console on most ships where they can print protolate related items. I'd say having a FoB medic and scientist possition would not be that bad if we have the random ruin event spawns. 
Though I feel like downsizing the cargo department to just a QM office, FOB and possibly a cargo shuttle would not go that well with myself. I honestly believe Tmtime's idea if integrated well with stations being cheaper and the Expressconsole to exactly as expensive as normaly in game (increased expressconsole costs will likely be an excuse not to use it at all) to be a good improvement.

We must also keep in mind with the RnD revamp the access to autolathes are going to be smaller so cargo will actually be able to handle Autolathe requests as usual.

**Comment by Qustinnus** [comment]
that still doesnt mean we'd need a big cargo department.

**Comment by Dennok** [comment]
Make stantion stock less random is god idea, but may be make random prices and amounts, so you olvays can buy what you naad for x10 price or travel half galaxy to where it cost halved.

**Comment by GoatMonarch** [comment]
> Make stancion stock less random is god idea, but may be make random prices and amounts, so you always can buy what you need for x10 price or travel half galaxy to where it cost halved.

This is a bit of an older thread but we believe we'll give the players the ability to purchase anything at any time (potentionaly some items will be only aviable from station stocks), and items from stations will be a lower cost due to the possibility to danger, the fact it's randomized chance wise, and that you need the crew to travel more. I'll likely close this down in two days and wait for Qustinnus to complete the combat system which will be more of a base before evaluating how to design the other departments around it.
